### ISSUE TITLE
error middle of smooth and lace 

### ISSUE THREAD

**Issue by cistarsa** [pangenome/smoothxg#65]
running smoothxg from [dockerfile](https://github.com/brettChapman/docker-builds/blob/master/smoothxg_builds/Dockerfile) on minimap2 -> seqwish gfa as
```
root@761a10378caf:/# smoothxg -g /tmp/L5.gfa -V -o smoothed_L5.gfa -m msa_L5.msa -t 16
```
with this stdout:
```
[smoothxg::main] loading graph
[smoothxg::main] prepping graph for smoothing
[smoothxg::prep] building path index
[smoothxg::prep] sorting graph
[odgi::path_linear_sgd] 1D path-guided SGD: 100.00% @ 6.05e+08/s elapsed: 00:00:00:00 remain: 00:00:00:00
[odgi::groom] grooming: 100.00% @ 1.64e+05/s elapsed: 00:00:00:00 remain: 00:00:00:00
[odgi::groom] organizing handles: 100.00% @ 6.14e+06/s elapsed: 00:00:00:00 remain: 00:00:00:00
[odgi::topological_order] sorting nodes: 100.00% @ 1.65e+05/s elapsed: 00:00:00:00 remain: 00:00:00:00
[smoothxg::prep] chopping graph to 100
[odgi::chop] 41317 node(s) to chop.
[smoothxg::prep] writing graph /tmp/L5.gfa.prep.gfa
[smoothxg::main] building xg index
[smoothxg::smoothable_blocks] computing blocks
[smoothxg::smoothable_blocks] computing blocks for 40099613 handles: 100.00% @ 6.62e+05/s elapsed: 00:00:01:00 remain: 00:00:00:00
[smoothxg::break_and_split_blocks] cutting blocks that contain sequences longer than max-poa-length (10000)
[smoothxg::break_and_split_blocks] splitting 400911 blocks at identity 0.50
[smoothxg::break_and_split_blocks] cutting and splitting 400911 blocks: 100.00% @ 2.28e+05/s elapsed: 00:00:00:01 remain: 00:00:00:00
[smoothxg::break_and_split_blocks] cut 0 blocks of which 0 had repeats
[smoothxg::break_and_split_blocks] split 23444 blocks
[smoothxg::smooth_and_lace] applying global abPOA to 434847 blocks: 57.08%Killed0e+02/s elapsed: 00:00:24:23 remain: 00:00:18:20
```

**Comment by cistarsa** [comment]
it's definitely maxing out the RAM on 16 CPUs of 128G...any suggestion on limiting this?

**Comment by AndreaGuarracino** [comment]
Hi @cistarsa, do you think you could share the dataset?

However, several issues related to time and memory usage have been fixed in the last few weeks. Over the next few days, we will address memory consumption further. We will release a new version soon that should solve your problem.

**Comment by cistarsa** [comment]
Happily! Glad to hear and indeed I rebuilt a docker container using git pull on Friday. Although, it got a bit further along it still killed..compressed file's still >1GB can I share it with you on google drive?

**Comment by AndreaGuarracino** [comment]
Yes, it would be great! Is the killer command line still this one

```smoothxg -g /tmp/L5.gfa -V -o smoothed_L5.gfa -m msa_L5.msa -t 16```

?

**Comment by ekg** [comment]
How did you prepare the alignments? I'm interested in what mapping command you used and any filtering you've done.

**Comment by ekg** [comment]
If the mappings allow repeats to collapse, it will generate graphs that are very deep in some places. These deep blocks require a lot of RAM for abPOA to process.

@AndreaGuarracino has developed a way to split the blocks efficiently into smaller problems using an edit and mash distance-based clustering approach. This can help to mitigate the issue.

The best way, however, is to make sure you are not seeing short or spurious mappings. To do this, in the past I have filtered short alignments from minimap2. This can be very difficult to control, but in general you should prevent alignments less than a pretty substantial length, maybe 50-200kb for a human chromosome, or higher if you wanted to directly build the graph whole genome. This in turn will remove many true alignments, making the graph represent variation simply due to the dropout of some alignments.

wfmash and edyeet implement an alternative alignment approach that lets us obtain a single global alignment for very long mappings between sequences of 10s of mbp. The goal is to mitigate these short mappings by being robust to relatively high divergence in regions around structural variation. The mappings are obtained using the mashmap2 algorithm, and finally base-level alignment is derived from WFA (in wfmash) or edlib (in edyeet). The input parameter space is pretty simple, in that you'd select a segment length for the seeding of alignments (this could be 1-100kb), a minimum pairwise identity (e.g. 95%),  and a number of secondary mappings for each segment.

**Comment by cistarsa** [comment]
> Yes, it would be great! Is the killer command line still this one
> 
> `smoothxg -g /tmp/L5.gfa -V -o smoothed_L5.gfa -m msa_L5.msa -t 16`
> 
> ?

yes, this is the command I used

**Comment by cistarsa** [comment]
> If the mappings allow repeats to collapse, it will generate graphs that are very deep in some places. These deep blocks require a lot of RAM for abPOA to process.
> 
> @AndreaGuarracino has developed a way to split the blocks efficiently into smaller problems using an edit and mash distance-based clustering approach. This can help to mitigate the issue.
> 
> The best way, however, is to make sure you are not seeing short or spurious mappings. To do this, in the past I have filtered short alignments from minimap2. This can be very difficult to control, but in general you should prevent alignments less than a pretty substantial length, maybe 50-200kb for a human chromosome, or higher if you wanted to directly build the graph whole genome. This in turn will remove many true alignments, making the graph represent variation simply due to the dropout of some alignments.
> 
> wfmash and edyeet implement an alternative alignment approach that lets us obtain a single global alignment for very long mappings between sequences of 10s of mbp. The goal is to mitigate spurious short mappings by being robust to relatively high divergence in regions around structural variation and driving the mapping and final base-level alignment through them efficiently. The mappings are obtained using the mashmap2 algorithm, a high-level alignment is derived with wflambda, and finally base-level alignment is derived from WFA (in wfmash) or edlib (in edyeet). The input parameter space is pretty simple, in that you'd select a segment length for the seeding of alignments (this could be 1-100kb), a minimum pairwise identity (e.g. 95%), and a number of secondary mappings for each segment.

I'm actuallly using a

**Comment by cistarsa** [comment]
I was able to run this on 32 cores using just over 266GB of memory
